# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-15 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('author', models.CharField(max_length=100)),
                ('author_org', models.CharField(max_length=200, verbose_name="Author's Organization")),
                ('description', models.TextField(help_text='Short description on front page')),
                ('url', models.URLField()),
                ('pic', models.ImageField(upload_to='tool_images')),
            ],
        ),
    ]
